# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.14'

steps:
- task: Xcode@5
  inputs:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: '8' # Options: 8, 9, default, specifyPath

#variables:
#  scheme: ''
#  sdk: 'iphoneos'
#  configuration: 'Release'

#steps:
#- task: Xcode@5
#  inputs:
#    sdk: '$(sdk)'
#    scheme: '$(scheme)'
#    configuration: '$(configuration)'
#    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
#    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
#    packageApp: false


