# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS-10.14'

steps:
- task: Xcode@5
  inputs:
    scheme: ''
    sdk: 'iphoneos'
    #configuration: 'Release'
    xcodeVersion: '9' # Options: 8, 9, default, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
#- task: CopyFiles@2
#  inputs:
#    contents: '**/*.ipa'
#    targetFolder: '$(Build.ArtifactStagingDirectory)'
    
#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)' 
#    includeRootFolder: true 
#    archiveType: 'zip' # Options: zip, 7z, tar, wim
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    targetFolder: $(Build.ArtifactStagingDirectory)   
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
    #fileCopyOptions: #Optiona1l
